version "3.3"

// ------------------------------------------------------------------------------------------------
//
//   NC HUD - Project Brutality Version 3
//
// ------------------------------------------------------------------------------------------------

class NCH_PBHUD : NCH_BaseHUD
{
	override void NCHF_AddAmmos ()
	{
		let player = CPlayer.mo;

		if (player is "Traditional")
		{
			NCHF_AddSingleAmmo("NewClip");
			NCHF_AddSingleAmmo("NewShell");
			NCHF_AddSingleAmmo("RocketAmmo");
			NCHF_AddSingleAmmo("Cell");
		}
		else if (player is "Purist")
		{
			NCHF_AddSingleAmmo("PistolBullets");
			NCHF_AddSingleAmmo("NewClip");
			NCHF_AddSingleAmmo("NewShell");
			NCHF_AddSingleAmmo("RocketAmmo");
			NCHF_AddSingleAmmo("Cell");
			NCHF_AddSingleAmmo("MiniHellRocketAmmo");
			NCHF_AddSingleAmmo("Gas");
			NCHF_AddSingleAmmo("BuzzSawAmmo");
			NCHF_AddSingleAmmo("HandGrenadeAmmo");
		}
		else
		{
			NCHF_AddSingleAmmo("PistolBullets");
			NCHF_AddSingleAmmo("NewShell");
			NCHF_AddSingleAmmo("NewClip");
			NCHF_AddSingleAmmo("HighExplosiveGrenadeRounds");
			NCHF_AddSingleAmmo("SpecialGrenadeRounds");
			NCHF_AddSingleAmmo("RocketAmmo");
			NCHF_AddSingleAmmo("Cell");
			NCHF_AddSingleAmmo("MiniHellRocketAmmo");
			NCHF_AddSingleAmmo("Gas");
			NCHF_AddSingleAmmo("DemonPower");
			NCHF_AddSingleAmmo("BuzzSawAmmo");
			NCHF_AddSingleAmmo("HandGrenadeAmmo");
			NCHF_AddSingleAmmo("MineAmmo");
		}
	}
}