version "3.3"

// ------------------------------------------------------------------------------------------------
//
//   NC HUD - BDLite
//
// ------------------------------------------------------------------------------------------------

class NCH_BDLiteHUD : NCH_BaseHUD
{
	override void NCHF_AddAmmos ()
	{
		NCHF_AddSingleAmmo("RifleAmmo");
		NCHF_AddSingleAmmo("Shell");
		NCHF_AddSingleAmmo("RocketAmmo");
		NCHF_AddSingleAmmo("PlasmaAmmo");
		NCHF_AddSingleAmmo("FlakAmmo");
		NCHF_AddSingleAmmo("GrenadeAmmo");
	}
}
