version "3.3"

// ------------------------------------------------------------------------------------------------
//
//   NC HUD - Weapons of Saturn
//
// ------------------------------------------------------------------------------------------------

class NCH_WOSHUD : NCH_BaseHUD
{
	override void NCHF_AddAmmos ()
	{
		NCHF_AddSingleAmmo("Clip");
		NCHF_AddSingleAmmo("Bullets");
		NCHF_AddSingleAmmo("Shell");
		NCHF_AddSingleAmmo("RifleAmmo");
		NCHF_AddSingleAmmo("Nato");
		NCHF_AddSingleAmmo("RocketAmmo");
		NCHF_AddSingleAmmo("Cell");
	}
}