version "3.2.5"

// ------------------------------------------------------------------------------------------------
//
//   NC HUD - Harmony
//
// ------------------------------------------------------------------------------------------------

class NCH_HarmonyStatusBar : NCH_BaseHUD
{
	override void NCHF_AddAmmos ()
	{
		NCHF_AddSingleAmmo("Clip");
		NCHF_AddSingleAmmo("Shell");
		NCHF_AddSingleAmmo("RocketAmmo");
		NCHF_AddSingleAmmo("Cell");
	}
}
