version "3.3"

// ------------------------------------------------------------------------------------------------
//
//   NC HUD - Kriegsland: Blutorden
//
// ------------------------------------------------------------------------------------------------

class NCH_KriegslandHUD : NCH_BaseHUD
{
	override void NCHF_Setup ()
	{
		nch_DrawMugShot = false;
	}

	override void NCHF_AddAmmos ()
	{
		NCHF_AddSingleAmmo("BOCL1");
		NCHF_AddSingleAmmo("BOHC1");
		NCHF_AddSingleAmmo("BOSH1");
		NCHF_AddSingleAmmo("BOEX1");
		NCHF_AddSingleAmmo("BOBT1");
		NCHF_AddSingleAmmo("BOCE1");
		NCHF_AddSingleAmmo("BOGR1");
	}
}
