version "3.3"

// ------------------------------------------------------------------------------------------------
//
//   NC HUD - Doom Incarnate
//
// ------------------------------------------------------------------------------------------------

class NCH_DoomIncarnateHUD : NCH_BaseHUD
{
	override void NCHF_AddAmmos ()
	{
		NCHF_AddSingleAmmo("9MMBullets");
		NCHF_AddSingleAmmo("MagnumBullets");
		NCHF_AddSingleAmmo("ShotgunShells");
		NCHF_AddSingleAmmo("NATOBullets");
		NCHF_AddSingleAmmo("VenomAmmo");
		NCHF_AddSingleAmmo("ExplosiveSlugs");
		NCHF_AddSingleAmmo("NapalmAmmo");
		NCHF_AddSingleAmmo("Battery");
		NCHF_AddSingleAmmo("FusionCell");
		NCHF_AddSingleAmmo("HatchetAmmo");
		NCHF_AddSingleAmmo("HandNadeAmmo");
	}
}