version "3.3"

// ------------------------------------------------------------------------------------------------
//
//   NC HUD - Arachnocide
//
// ------------------------------------------------------------------------------------------------

class NCH_ArachnocideHUD : NCH_BaseHUD
{
	override void NCHF_AddAmmos ()
	{
		NCHF_AddSingleAmmo("ARCL1");
		NCHF_AddSingleAmmo("ARRV1");
		NCHF_AddSingleAmmo("ARSH1");
		NCHF_AddSingleAmmo("ARHC1");
		NCHF_AddSingleAmmo("AREX1");
		NCHF_AddSingleAmmo("ARBT1");
		NCHF_AddSingleAmmo("ARTR1");
		NCHF_AddSingleAmmo("ARFL1");
	}
}
