version "3.2.5"

// ------------------------------------------------------------------------------------------------
//
//   NC HUD - Dusted's Pandemonia
//
// ------------------------------------------------------------------------------------------------

class NCH_PandemoniaHUD : NCH_BaseHUD
{
	override void NCHF_InGameSetup ()
	{
		NCHF_AddToAmmoListOverride("NewClip");
		NCHF_AddToAmmoListOverride("NewShell");
		NCHF_AddToAmmoListOverride("NewRocketAmmo");
		NCHF_AddToAmmoListOverride("NewCell");
	}
}
