version "3.2.5"

// ------------------------------------------------------------------------------------------------
//
//   NC HUD - Dusted's Pandemonia
//
// ------------------------------------------------------------------------------------------------

class NCH_PandemoniaHUD : NCH_BaseHUD
{
	override void NCHF_AddAmmos ()
	{
		NCHF_AddSingleAmmo("NewClip");
		NCHF_AddSingleAmmo("NewShell");
		NCHF_AddSingleAmmo("NewRocketAmmo");
		NCHF_AddSingleAmmo("NewCell");
	}
}
